# Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from typing import Any

import legate.core
import pyarrow as pa
from legate.core import StoreTarget

class LogicalColumn:
    def __init__(self, obj: Any, *, scalar: bool = False) -> None: ...
    @staticmethod
    def from_cudf(col: Any) -> LogicalColumn: ...
    @staticmethod
    def from_arrow(col: pa.Array) -> LogicalColumn: ...
    @staticmethod
    def empty_like_logical_column(col: LogicalColumn) -> LogicalColumn: ...
    def num_rows(self) -> int: ...
    def cudf_type(self) -> Any: ...
    def dtype(self) -> pa.DataType: ...
    def is_scalar(self) -> bool: ...
    def get_logical_array(
        self, *, check_dtype: bool = False
    ) -> legate.core.LogicalArray: ...
    @property
    def __legate_data_interface__(self) -> dict: ...
    def to_array(self, *, writeable=False) -> Any: ...
    def get_arrow(self) -> pa.array: ...
    def to_cudf(self) -> Any: ...
    def to_cudf_scalar(self) -> Any: ...
    def offload_to(target_mem: StoreTarget) -> None: ...
    def slice(self, slice_) -> LogicalColumn: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, slice_) -> LogicalColumn: ...
    def add_as_next_task_input(self, task: legate.core.AutoTask) -> None: ...
    def add_as_next_task_output(self, task: legate.core.AutoTask) -> None: ...
