# Copyright (c) 2023, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--resolve-all-configs"]
        types_or: [python, cython, pyi]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: ["--config", "python/pyproject.toml", --fix]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--config", "python/pyproject.toml"]
  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.16.2
    hooks:
          - id: cython-lint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'
    hooks:
      - id: mypy
        additional_dependencies: [types-cachetools]
        args: ["--ignore-missing-imports", "python/legate_dataframe"]
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.3
    hooks:
      - id: clang-format
        types_or: [c, c++, cuda]
  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v0.4.0
    hooks:
      - id: verify-copyright
  - repo: local
    hooks:
      - id: cmake-format
        name: cmake-format
        entry: ./scripts/run-cmake-format.sh cmake-format
        language: python
        types: [cmake]
        # Note that pre-commit autoupdate does not update the versions
        # of dependencies, so we'll have to update this manually.
        additional_dependencies:
          - cmakelang==0.6.13
        verbose: true
        require_serial: true
      - id: cmake-lint
        name: cmake-lint
        entry: ./scripts/run-cmake-format.sh cmake-lint
        language: python
        types: [cmake]
        # Note that pre-commit autoupdate does not update the versions
        # of dependencies, so we'll have to update this manually.
        additional_dependencies:
          - cmakelang==0.6.13
        verbose: true
        require_serial: true
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: ["--toml", "pyproject.toml"]
        exclude: |
          (?x)^(
            ^CHANGELOG.md$
          )
  - repo: https://github.com/rapidsai/dependency-file-generator
    rev: v1.17.0
    hooks:
        - id: rapids-dependency-file-generator
          args: ["--clean"]

default_language_version:
      python: python3
