/*
 * Copyright (c) 2025, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * THIS FILE IS HACK COPY FROM LEGATE.  The only chang is the last
 * additional undef!
 */

/**
 * \file legion_defines.h
 * Public-facing definitions of variables configured at build time
 * DO NOT EDIT THIS FILE WITHOUT CHANGING runtime.mk ALSO
 */

/********************** IMPORTANT **************************
 *
 * This file is PURE C, **NOT** C++. Keep any C++-isms in
 * legion_types.h, or elsewhere.
 *
 ******************** IMPORTANT ****************************/

#define LEGION_VERSION "25.10.0"

/* #undef DEBUG_LEGION */

/* #undef LEGION_PRIVILEGE_CHECKS */

/* #undef LEGION_BOUNDS_CHECKS */

#define LEGION_MAX_DIM 6

#define LEGION_MAX_FIELDS 256

#define LEGION_DEFAULT_LOCAL_FIELDS (0)

#define LEGION_MAX_NUM_NODES 1024

#define LEGION_MAX_NUM_PROCS 64

#define LEGION_USE_CUDA

/* #undef LEGION_GPU_REDUCTIONS */

/* #undef LEGION_USE_ZLIB */

#define LEGION_REDOP_COMPLEX

#define LEGION_REDOP_HALF

/* #undef LEGION_WARNINGS_FATAL */

/* #undef LEGION_USE_HDF5 */

/* #undef LEGION_SPY */

/* #undef LEGION_USE_HIP */

#define LEGION_USE_LIBDL

#undef LEGION_REDOP_HALF
